
(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('space'),ctx=canvas.getContext('2d'),TAU=Math.PI*2,BASE=13500,MAX=24;
const palettes={dusk:['#c9b8ff','#b9e9ca','#f5d6a1','#eebcac','#a9c8ec','#d8b2e8'],aurora:['#83e8db','#8cbcff','#c9b8ff','#a7f4cb','#96d7ed','#b6a2ff'],ember:['#ffd18d','#f19e9e','#ecb7db','#ffba85','#efdcb1','#ea97b0']};
let config={preset:'harmony',palette:'dusk',gravity:1,speed:1,extras:[]},planets=[],paused=matchMedia('(prefers-reduced-motion: reduce)').matches,sound=false,audio,master,w=0,h=0,dpr=1,scale=1,last=0,elapsed=0,completed=0,drag=null,toastTimer,storageOK=true,resetAction=null;
function valid(c){return c&&['harmony','bloom','wild'].includes(c.preset)&&Object.hasOwn(palettes,c.palette)&&Number.isFinite(c.gravity)&&c.gravity>=.4&&c.gravity<=2&&Number.isFinite(c.speed)&&c.speed>=.2&&c.speed<=2&&Array.isArray(c.extras)&&c.extras.length<=18&&c.extras.every(p=>Array.isArray(p)&&p.length===4&&p.every(v=>Number.isFinite(v)&&Math.abs(v)<2000));}
let initialMessage='';try{const hash=location.hash.slice(1);if(hash){let c=JSON.parse(decodeURIComponent(hash));if(!valid(c))throw Error();config=c;initialMessage='A shared universe, now in your hands.';}else{let c=JSON.parse(localStorage.getItem('orbit-garden-v1'));if(valid(c))config=c;}}catch{initialMessage='Could not restore that garden. A fresh universe is ready.';}
function notify(msg){$('toast').textContent=msg;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3500);}
function save(){try{localStorage.setItem('orbit-garden-v1',JSON.stringify(config));storageOK=true;}catch{storageOK=false;}$('saveState').textContent=storageOK?'saved locally':'session only';if(location.hash)history.replaceState(null,'',location.pathname+location.search);}
function make(x,y,vx,vy,i){return{x,y,vx,vy,i,trail:[],travel:0,angle:Math.atan2(y,x),noteAt:-9};}
function seeds(){let a=[];for(let i=0;i<6;i++){let angle=i*TAU/6+.4,r=72+i*25;if(config.preset==='bloom'){r=172;angle=i*TAU/6;}if(config.preset==='wild'){r=80+i*23;angle=i*2.399;}let factor=config.preset==='bloom'?.57:config.preset==='wild'?.56+i*.11:1;let v=Math.sqrt(BASE*config.gravity/r)*factor;a.push(make(Math.cos(angle)*r,Math.sin(angle)*r,-Math.sin(angle)*v,Math.cos(angle)*v,i));}return a;}
function updateUI(){document.querySelectorAll('[data-preset]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.preset===config.preset));document.querySelectorAll('[data-palette]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.palette===config.palette));['gravity','speed'].forEach(k=>{$(k).value=config[k];$(k+'Out').value=config[k].toFixed(1)+'×';});$('sceneName').textContent=({harmony:'01 — HARMONY',bloom:'02 — BLOOM',wild:'03 — WILD'})[config.preset];$('count').textContent=planets.length;$('undo').disabled=!config.extras.length;$('launch').disabled=planets.length>=MAX;$('play').textContent=paused?'▶':'Ⅱ';$('play').setAttribute('aria-label',paused?'Play simulation':'Pause simulation');$('liveLabel').textContent=paused?'PAUSED':'LIVE';$('liveDot').style.background=paused?'#929aae':'#b9e9ca';$('gardenState').textContent=paused?'Resting':'Growing';$('sound').setAttribute('aria-checked',sound);$('soundState').textContent=sound?'Pentatonic':'Silent';$('soundUnit').textContent=sound?'in C major':'for now';}
function warmTrails(){for(const p of planets){let x=p.x,y=p.y,vx=p.vx,vy=p.vy,t=[];for(let j=0;j<360;j++){t.push([x,y]);let [ax,ay]=acceleration(x,y);vx-=ax*.08;vy-=ay*.08;x-=vx*.16;y-=vy*.16;[ax,ay]=acceleration(x,y);vx-=ax*.08;vy-=ay*.08;}p.trail=t.reverse();}}
function reset(){planets=seeds();config.extras.forEach((p,i)=>planets.push(make(...p,i+6)));warmTrails();completed=0;elapsed=0;$('orbits').textContent='0';updateUI();save();}
function resize(){let rect=canvas.getBoundingClientRect();w=rect.width;h=rect.height;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);scale=Math.min(w,h)/530;}
new ResizeObserver(resize).observe(canvas);
function acceleration(x,y){let r2=x*x+y*y+100,f=-BASE*config.gravity/Math.pow(r2,1.5);return[x*f,y*f];}
function step(dt){elapsed+=dt;for(const p of planets){let [ax,ay]=acceleration(p.x,p.y);p.vx+=ax*dt/2;p.vy+=ay*dt/2;p.x+=p.vx*dt;p.y+=p.vy*dt;[ax,ay]=acceleration(p.x,p.y);p.vx+=ax*dt/2;p.vy+=ay*dt/2;let angle=Math.atan2(p.y,p.x),delta=Math.atan2(Math.sin(angle-p.angle),Math.cos(angle-p.angle));p.travel+=delta;if(Math.abs(p.travel)>=TAU){completed++;p.travel-=Math.sign(p.travel)*TAU;$('orbits').textContent=completed;}if(p.angle<0&&angle>=0&&p.x>0&&elapsed-p.noteAt>1){playNote(p.i);p.noteAt=elapsed;}p.angle=angle;}}
function draw(){ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#0d111a';ctx.fillRect(0,0,w,h);let glow=ctx.createRadialGradient(w*.51,h*.48,0,w*.5,h*.5,Math.max(w,h)*.55);glow.addColorStop(0,'#23283e66');glow.addColorStop(.55,'#171d3022');glow.addColorStop(1,'#0d111a00');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);
for(let i=0;i<100;i++){let x=((Math.sin(i*127.1+14)*43758.5453)%1+1)%1*w,y=((Math.sin(i*269.5+9)*43758.5453)%1+1)%1*h;ctx.globalAlpha=.2+(i%5)*.07;ctx.fillStyle='#bcc8e7';ctx.fillRect(x,y,i%9===0?1.5:1,i%9===0?1.5:1);}ctx.globalAlpha=1;ctx.save();ctx.translate(w/2,h/2+6);ctx.scale(scale,scale);
ctx.strokeStyle='#a7b4d011';ctx.lineWidth=.8/scale;[72,122,172,222].forEach(r=>{ctx.beginPath();ctx.arc(0,0,r,0,TAU);ctx.stroke();});ctx.setLineDash([2,8]);ctx.beginPath();ctx.moveTo(-260,0);ctx.lineTo(260,0);ctx.moveTo(0,-260);ctx.lineTo(0,260);ctx.stroke();ctx.setLineDash([]);
if(sound){ctx.strokeStyle='#c9b8ff35';ctx.beginPath();ctx.moveTo(22,0);ctx.lineTo(250,0);ctx.stroke();}
for(let i=0;i<planets.length;i++){let p=planets[i],color=palettes[config.palette][p.i%6];if(!paused){p.trail.push([p.x,p.y]);if(p.trail.length>480)p.trail.shift();}if(p.trail.length>1){for(let j=1;j<p.trail.length;j++){ctx.globalAlpha=(j/p.trail.length)*.7;ctx.strokeStyle=color;ctx.lineWidth=1.2/scale;ctx.beginPath();ctx.moveTo(...p.trail[j-1]);ctx.lineTo(...p.trail[j]);ctx.stroke();}}ctx.globalAlpha=1;
// A faint orbit preview gives an immediately legible garden, even before trails grow.
if(config.preset==='harmony'&&i<6){ctx.globalAlpha=.16;ctx.strokeStyle=color;ctx.beginPath();ctx.arc(0,0,72+i*25,0,TAU);ctx.stroke();ctx.globalAlpha=1;}
ctx.shadowColor=color;ctx.shadowBlur=15;ctx.fillStyle=color;ctx.beginPath();ctx.arc(p.x,p.y,3.2+(p.i%3)*.7,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.globalAlpha=.17;ctx.beginPath();ctx.arc(p.x,p.y,9+(p.i%3),0,TAU);ctx.fill();ctx.globalAlpha=1;
// Offscreen bodies remain discoverable via edge indicators.
let limitX=w/(2*scale)-15,limitY=h/(2*scale)-20;if(Math.abs(p.x)>limitX||Math.abs(p.y)>limitY){let f=Math.min(limitX/Math.abs(p.x),limitY/Math.abs(p.y));ctx.fillStyle=color;ctx.beginPath();ctx.arc(p.x*f,p.y*f,2.5,0,TAU);ctx.fill();}}
let sun=ctx.createRadialGradient(0,0,3,0,0,45);sun.addColorStop(0,'#f5d6a130');sun.addColorStop(1,'#f5d6a100');ctx.fillStyle=sun;ctx.beginPath();ctx.arc(0,0,45,0,TAU);ctx.fill();ctx.strokeStyle='#f5d6a130';ctx.beginPath();ctx.arc(0,0,18,0,TAU);ctx.stroke();ctx.shadowColor='#f5d6a1';ctx.shadowBlur=22;ctx.fillStyle='#f5d6a1';ctx.beginPath();ctx.arc(0,0,9,0,TAU);ctx.fill();ctx.shadowBlur=0;
if(drag){ctx.strokeStyle='#ffffffaa';ctx.lineWidth=1.5/scale;ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(drag.x,drag.y);ctx.lineTo(drag.ex,drag.ey);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(drag.x,drag.y,4,0,TAU);ctx.fill();let vx=(drag.ex-drag.x)*.13,vy=(drag.ey-drag.y)*.13,x=drag.x,y=drag.y;ctx.globalAlpha=.3;ctx.beginPath();ctx.moveTo(x,y);for(let i=0;i<100;i++){let[a,b]=acceleration(x,y);vx+=a*.12;vy+=b*.12;x+=vx*.12;y+=vy*.12;ctx.lineTo(x,y);}ctx.stroke();ctx.globalAlpha=1;}
ctx.restore();}
function frame(time){let dt=last?Math.min((time-last)/1000,.04):0;last=time;if(!paused&&!document.hidden){for(let i=0;i<4;i++)step(dt*config.speed*5/4);}draw();requestAnimationFrame(frame);}
function launch(p){if(planets.length>=MAX){notify('Your garden is full: 24 planets. Undo a launch or start fresh.');return;}config.extras.push(p);planets.push(make(...p,planets.length));updateUI();save();notify(paused?'Planet added. Press play to set it in motion.':'A new little world. Welcome to the universe.');}
function randomLaunch(){let a=Math.random()*TAU,r=100+Math.random()*95,v=Math.sqrt(BASE*config.gravity/r)*(.82+Math.random()*.25);launch([Math.cos(a)*r,Math.sin(a)*r,-Math.sin(a)*v,Math.cos(a)*v]);}
function position(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left-w/2)/scale,y:(e.clientY-r.top-h/2-6)/scale};}
canvas.addEventListener('pointerdown',e=>{if(e.button!==0||drag)return;let p=position(e);drag={...p,ex:p.x,ey:p.y,id:e.pointerId};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;let p=position(e);drag.ex=p.x;drag.ey=p.y;});canvas.addEventListener('pointerup',e=>{if(!drag||e.pointerId!==drag.id)return;let d=drag;drag=null;if(Math.hypot(d.x,d.y)<24){notify('Give your planet a little space. Launch farther from the sun.');return;}let dx=d.ex-d.x,dy=d.ey-d.y;if(Math.hypot(dx,dy)<5){let v=Math.sqrt(BASE*config.gravity/Math.hypot(d.x,d.y));launch([d.x,d.y,-d.y/Math.hypot(d.x,d.y)*v,d.x/Math.hypot(d.x,d.y)*v]);}else{let f=Math.min(1,320/Math.hypot(dx,dy));launch([d.x,d.y,dx*.13*f,dy*.13*f]);}});canvas.addEventListener('pointercancel',()=>drag=null);
function togglePause(){paused=!paused;updateUI();}
$('play').onclick=togglePause;$('launch').onclick=randomLaunch;$('undo').onclick=()=>{if(!config.extras.length)return;config.extras.pop();planets.pop();updateUI();save();notify('Last launch undone.');};
function askReset(action){resetAction=action;$('confirmDialog').showModal();$('cancelReset').focus();}$('reset').onclick=()=>askReset(()=>{config.extras=[];reset();notify('A fresh start. Possibility awaits.');});$('confirmReset').onclick=()=>{$('confirmDialog').close();resetAction?.();};$('cancelReset').onclick=()=>$('confirmDialog').close();
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{if(config.preset===b.dataset.preset)return;askReset(()=>{config.preset=b.dataset.preset;config.extras=[];reset();notify('A new pattern, a new possibility.');});});document.querySelectorAll('[data-palette]').forEach(b=>b.onclick=()=>{config.palette=b.dataset.palette;updateUI();save();});['gravity','speed'].forEach(k=>$(k).oninput=()=>{config[k]=Number($(k).value);$(k+'Out').value=config[k].toFixed(1)+'×';save();});
async function toggleSound(){try{if(!sound){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error();if(!audio){audio=new AC();master=audio.createGain();master.gain.value=.15;master.connect(audio.destination);}await audio.resume();if(audio.state!=='running')throw Error();sound=true;master.gain.setTargetAtTime(.15,audio.currentTime,.04);playNote(0);notify('Sound on. Listen as planets cross the right-hand ray.');}else{sound=false;master.gain.setTargetAtTime(0,audio.currentTime,.04);notify('Sound off. A quiet little cosmos.');}updateUI();}catch{sound=false;updateUI();notify('Audio is unavailable. Try another browser or check sound permissions.');}}
function playNote(i){if(!sound||!audio||audio.state!=='running'||document.hidden)return;let freq=[261.63,293.66,329.63,392,440,523.25][i%6],now=audio.currentTime,osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.value=freq;gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.28,now+.02);gain.gain.exponentialRampToValueAtTime(.001,now+1.8);osc.connect(gain);gain.connect(master);osc.start(now);osc.stop(now+1.9);osc.onended=()=>{osc.disconnect();gain.disconnect();};}
$('sound').onclick=toggleSound;$('help').onclick=()=>$('helpDialog').showModal();$('closeHelp').onclick=()=>$('helpDialog').close();$('closeShare').onclick=()=>$('shareDialog').close();
$('share').onclick=async()=>{let url=location.origin+location.pathname+'#'+encodeURIComponent(JSON.stringify(config));try{await navigator.clipboard.writeText(url);notify('Universe link copied. Send a little wonder.');}catch{$('shareUrl').value=url;$('shareDialog').showModal();$('shareUrl').select();}};
$('snapshot').onclick=()=>{let out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;let c=out.getContext('2d');c.drawImage(canvas,0,0);c.fillStyle='#f0eee9';c.font=`${18*dpr}px sans-serif`;c.fillText('O R B I T',24*dpr,34*dpr);c.fillStyle='#a1a6b8';c.font=`${10*dpr}px sans-serif`;c.fillText('A TINY UNIVERSE. ENTIRELY YOURS.',24*dpr,out.height-22*dpr);out.toBlob(blob=>{if(!blob){notify('Could not create your postcard. Please try again.');return;}let a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='orbit-my-little-universe.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);notify('Your cosmic postcard is ready.');},'image/png');};
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||/INPUT|SELECT|TEXTAREA|BUTTON/.test(e.target.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$('undo').click();return;}if(e.ctrlKey||e.metaKey||e.altKey)return;if(e.code==='Space'){e.preventDefault();togglePause();}else if(e.key.toLowerCase()==='l')randomLaunch();else if(e.key.toLowerCase()==='m')toggleSound();else if(e.key.toLowerCase()==='r')$('reset').click();});
document.addEventListener('visibilitychange',()=>{last=0;if(master)master.gain.setTargetAtTime(document.hidden?0:sound?.15:0,audio.currentTime,.04);});
reset();resize();requestAnimationFrame(frame);if(initialMessage)notify(initialMessage);
})();
