process.on('uncaughtExceptionMonitor', e => console.log('::error::'+String(e.stack).replaceAll('%','%25').replaceAll('\n','%0A').replaceAll('\r','%0D')));
import { chromium } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readFile, mkdir, writeFile } from 'node:fs/promises';

await mkdir('test-results', { recursive: true });
const html = await readFile('index.html');
const server = createServer(async (req,res) => {
 const name = new URL(req.url, 'http://localhost').pathname;
 if(name === '/styles.css' || name === '/app.js') { res.writeHead(200, {'Content-Type':name.endsWith('.css')?'text/css':'text/javascript'});res.end(await readFile('.'+name)); }
 else { res.writeHead(200, {'Content-Type':'text/html; charset=utf-8'});res.end(html); }
});
await new Promise(resolve => server.listen(4173, '127.0.0.1', resolve));
const browser = await chromium.launch();
const errors = [];
const results = [];
const base = process.env.SITE_URL || 'http://127.0.0.1:4173/';
const check = (name, condition) => { assert.ok(condition, name); results.push(name); console.log('PASS:', name); };
try {
 const context = await browser.newContext({viewport:{width:1440,height:1050}, permissions:['clipboard-read','clipboard-write']});
 const page = await context.newPage();
 page.on('pageerror', e => errors.push(e.message));
 const response = await page.goto(base);
 check('HTTP success', response.ok());
 await page.waitForFunction(() => document.querySelector('#space').width > 0);
 await page.waitForTimeout(600);
 check('Initial garden has six planets', await page.locator('#count').innerText() === '6');
 check('Desktop has no horizontal overflow', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
 await page.screenshot({path:'test-results/desktop.png',fullPage:true});
 await page.locator('#launch').click();
 check('Launch adds a planet', await page.locator('#count').innerText() === '7');
 await page.locator('#undo').click();
 check('Undo removes last launch', await page.locator('#count').innerText() === '6');
 await page.locator('#play').click();
 check('Pause updates system status', await page.locator('#liveLabel').innerText() === 'PAUSED');
 await page.locator('#play').click();
 await page.locator('[data-palette="aurora"]').click();
 await page.locator('#gravity').evaluate(e => e.value = '1.4');
 await page.locator('#gravity').dispatchEvent('input');
 await page.locator('#speed').evaluate(e => e.value = '0.8');
 await page.locator('#speed').dispatchEvent('input');
 check('Gravity output updates', await page.locator('#gravityOut').innerText() === '1.4×');
 await page.reload();
 check('Settings persist', await page.locator('#gravity').inputValue() === '1.4');
 check('Palette persists', await page.locator('[data-palette="aurora"]').getAttribute('aria-pressed') === 'true');
 await page.locator('[data-preset="bloom"]').click();
 await page.locator('#cancelReset').click();
 check('Preset change can be cancelled', (await page.locator('#sceneName').innerText()).includes('HARMONY'));
 await page.locator('[data-preset="bloom"]').click();
 await page.locator('#confirmReset').click();
 check('Bloom preset activates', (await page.locator('#sceneName').innerText()).includes('BLOOM'));
 await page.screenshot({path:'test-results/bloom.png',fullPage:true});
 const box = await page.locator('#space').boundingBox();
 await page.mouse.move(box.x+box.width*.7,box.y+box.height*.45);
 await page.mouse.down();
 await page.mouse.move(box.x+box.width*.7+30,box.y+box.height*.45+60,{steps:5});
 await page.mouse.up();
 check('Canvas drag launches', await page.locator('#count').innerText() === '7');
 await page.locator('#sound').click();
 await page.waitForFunction(() => document.querySelector('#sound').getAttribute('aria-checked') === 'true');
 check('Audio enables after gesture', await page.locator('#soundState').innerText() === 'Pentatonic');
 await page.locator('#sound').click();
 check('Audio can be muted', await page.locator('#sound').getAttribute('aria-checked') === 'false');
 const downloadPromise = page.waitForEvent('download');
 await page.locator('#snapshot').click();
 const download = await downloadPromise;
 check('PNG postcard download', download.suggestedFilename() === 'orbit-my-little-universe.png');
 await download.saveAs('test-results/postcard.png');
 await page.locator('#share').click();
 const link = await page.evaluate(() => navigator.clipboard.readText());
 check('Share contains initial conditions', JSON.parse(decodeURIComponent(new URL(link).hash.slice(1))).extras.length === 1);
 const shared = await context.newPage();
 await shared.goto(link);
 check('Shared universe restores planet', await shared.locator('#count').innerText() === '7');
 check('Shared universe restores preset', (await shared.locator('#sceneName').innerText()).includes('BLOOM'));
 await shared.close();
 await page.evaluate(() => document.activeElement.blur());
 await page.keyboard.press('Space');
 check('Space keyboard shortcut', await page.locator('#liveLabel').innerText() === 'PAUSED');
 await page.keyboard.press('l');
 check('Keyboard launch', await page.locator('#count').innerText() === '8');
 await page.keyboard.press('Control+z');
 check('Keyboard undo', await page.locator('#count').innerText() === '7');
 await page.locator('#help').click();
 check('Help opens', await page.locator('#helpDialog').evaluate(e => e.open));
 await page.keyboard.press('Escape');
 check('Escape dismisses help', !(await page.locator('#helpDialog').evaluate(e => e.open)));
 const axe = await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
 await writeFile('test-results/accessibility.json', JSON.stringify(axe.violations,null,2));
 console.log('Accessibility violations:', JSON.stringify(axe.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}))));
 check('No serious accessibility violations', !axe.violations.some(v => ['critical','serious'].includes(v.impact)));
 await page.locator('#reset').click();
 await page.locator('#confirmReset').click();
 check('Reset returns to six planets', await page.locator('#count').innerText() === '6');
 for(let i=0;i<18;i++) await page.locator('#launch').click();
 check('Planet limit prevents excess launches', await page.locator('#count').innerText() === '24' && await page.locator('#launch').isDisabled());
 await page.goto(base+'#not-valid-json');
 check('Malformed share recovers safely', await page.locator('#count').innerText() === '6');
 await page.evaluate(() => localStorage.setItem('orbit-garden-v1','invalid'));
 await page.goto(base);
 check('Corrupt saved state recovers', await page.locator('#count').innerText() === '6');
 for(const width of [390,320,768]) {
  const mobile = await browser.newContext({viewport:{width,height:844},isMobile:width<500,hasTouch:true});
  const p = await mobile.newPage();
  p.on('pageerror',e=>errors.push(e.message));
  await p.goto(base);
  check(`No horizontal overflow at ${width}px`, await p.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await p.locator('#launch').click();
  check(`Launch works at ${width}px`, await p.locator('#count').innerText() === '7');
  await p.screenshot({path:`test-results/mobile-${width}.png`,fullPage:true});
  await mobile.close();
 }
 const reduced = await browser.newContext({reducedMotion:'reduce'});
 const rp = await reduced.newPage();
 await rp.goto(base);
 check('Reduced motion starts paused', await rp.locator('#liveLabel').innerText() === 'PAUSED');
 await reduced.close();
 check('No JavaScript runtime errors', errors.length === 0);
 await writeFile('test-results/results.json',JSON.stringify({passed:results,errors},null,2));
 console.log(`${results.length} checks passed.`);
} finally {
 await browser.close();
 await new Promise(resolve=>server.close(resolve));
}
